//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.12 at 05:22:22 PM IST 
//


package com.zillow._static.xsd.searchresults;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.zillow._static.xsd.searchresults package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.zillow._static.xsd.searchresults
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Searchresults }
     * 
     */
    public Searchresults createSearchresults() {
        return new Searchresults();
    }

    /**
     * Create an instance of {@link Searchresults.Response }
     * 
     */
    public Searchresults.Response createSearchresultsResponse() {
        return new Searchresults.Response();
    }

    /**
     * Create an instance of {@link Searchresults.Request }
     * 
     */
    public Searchresults.Request createSearchresultsRequest() {
        return new Searchresults.Request();
    }

    /**
     * Create an instance of {@link Searchresults.Response.Results }
     * 
     */
    public Searchresults.Response.Results createSearchresultsResponseResults() {
        return new Searchresults.Response.Results();
    }

}
