//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.12 at 05:22:22 PM IST 
//


package com.zillow._static.xsd.regionchildren;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.zillow._static.xsd.regionchildren package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Regionchildren_QNAME = new QName("http://www.zillow.com/static/xsd/RegionChildren.xsd", "regionchildren");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.zillow._static.xsd.regionchildren
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegionchildrenResultType }
     * 
     */
    public RegionchildrenResultType createRegionchildrenResultType() {
        return new RegionchildrenResultType();
    }

    /**
     * Create an instance of {@link RegionchildrenResultType.Response }
     * 
     */
    public RegionchildrenResultType.Response createRegionchildrenResultTypeResponse() {
        return new RegionchildrenResultType.Response();
    }

    /**
     * Create an instance of {@link RegionchildrenResultType.Response.List }
     * 
     */
    public RegionchildrenResultType.Response.List createRegionchildrenResultTypeResponseList() {
        return new RegionchildrenResultType.Response.List();
    }

    /**
     * Create an instance of {@link RegionchildrenResultType.Response.List.Region }
     * 
     */
    public RegionchildrenResultType.Response.List.Region createRegionchildrenResultTypeResponseListRegion() {
        return new RegionchildrenResultType.Response.List.Region();
    }

    /**
     * Create an instance of {@link RegionchildrenResultType.Request }
     * 
     */
    public RegionchildrenResultType.Request createRegionchildrenResultTypeRequest() {
        return new RegionchildrenResultType.Request();
    }

    /**
     * Create an instance of {@link RegionchildrenResultType.Response.List.Region.Zindex }
     * 
     */
    public RegionchildrenResultType.Response.List.Region.Zindex createRegionchildrenResultTypeResponseListRegionZindex() {
        return new RegionchildrenResultType.Response.List.Region.Zindex();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegionchildrenResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.zillow.com/static/xsd/RegionChildren.xsd", name = "regionchildren")
    public JAXBElement<RegionchildrenResultType> createRegionchildren(RegionchildrenResultType value) {
        return new JAXBElement<RegionchildrenResultType>(_Regionchildren_QNAME, RegionchildrenResultType.class, null, value);
    }

}
