//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.11 at 03:39:13 PM IST 
//


package com.zillow._static.xsd.comps;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.zillow._static.xsd.comps package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.zillow._static.xsd.comps
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Comps }
     * 
     */
    public Comps createComps() {
        return new Comps();
    }

    /**
     * Create an instance of {@link Comps.Response }
     * 
     */
    public Comps.Response createCompsResponse() {
        return new Comps.Response();
    }

    /**
     * Create an instance of {@link Comps.Response.Properties }
     * 
     */
    public Comps.Response.Properties createCompsResponseProperties() {
        return new Comps.Response.Properties();
    }

    /**
     * Create an instance of {@link Comps.Request }
     * 
     */
    public Comps.Request createCompsRequest() {
        return new Comps.Request();
    }

    /**
     * Create an instance of {@link Comps.Response.Properties.Comparables }
     * 
     */
    public Comps.Response.Properties.Comparables createCompsResponsePropertiesComparables() {
        return new Comps.Response.Properties.Comparables();
    }

}
