//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.11 at 03:39:13 PM IST 
//


package com.zillow._static.xsd.zestimate;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.zillow._static.xsd.zillowtypes.DetailedProperty;
import com.zillow._static.xsd.zillowtypes.Message;


/**
 * <p>Java class for zestimateResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="zestimateResultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="request">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="zpid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="message" type="{http://www.zillow.com/static/xsd/ZillowTypes.xsd}Message"/>
 *         &lt;element name="response" type="{http://www.zillow.com/static/xsd/ZillowTypes.xsd}DetailedProperty" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "zestimateResultType", propOrder = {
    "request",
    "message",
    "response"
})
public class ZestimateResultType {

    @XmlElement(required = true)
    protected ZestimateResultType.Request request;
    @XmlElement(required = true)
    protected Message message;
    protected DetailedProperty response;

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link ZestimateResultType.Request }
     *     
     */
    public ZestimateResultType.Request getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZestimateResultType.Request }
     *     
     */
    public void setRequest(ZestimateResultType.Request value) {
        this.request = value;
    }

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link Message }
     *     
     */
    public Message getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link Message }
     *     
     */
    public void setMessage(Message value) {
        this.message = value;
    }

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link DetailedProperty }
     *     
     */
    public DetailedProperty getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link DetailedProperty }
     *     
     */
    public void setResponse(DetailedProperty value) {
        this.response = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="zpid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "zpid"
    })
    public static class Request {

        @XmlElement(required = true)
        protected String zpid;

        /**
         * Gets the value of the zpid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getZpid() {
            return zpid;
        }

        /**
         * Sets the value of the zpid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setZpid(String value) {
            this.zpid = value;
        }

    }

}
