//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.07 at 02:14:39 PM IST 
//


package com.zillow._static.xsd.zillowtypes;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChartVariant.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ChartVariant">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="homedetails"/>
 *     &lt;enumeration value="showcase"/>
 *     &lt;enumeration value="detailed"/>
 *     &lt;enumeration value="seo"/>
 *     &lt;enumeration value="partner"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "ChartVariant")
@XmlEnum
public enum ChartVariant {

    @XmlEnumValue("homedetails")
    HOMEDETAILS("homedetails"),
    @XmlEnumValue("showcase")
    SHOWCASE("showcase"),
    @XmlEnumValue("detailed")
    DETAILED("detailed"),
    @XmlEnumValue("seo")
    SEO("seo"),
    @XmlEnumValue("partner")
    PARTNER("partner");
    private final String value;

    ChartVariant(String v) {
        value = v;
    }

    public static ChartVariant fromValue(String v) {
        for (ChartVariant c : ChartVariant.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public String value() {
        return value;
    }

}
