//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.07 at 02:14:39 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.zillow.com/static/xsd/ZillowTypes.xsd")
package com.zillow._static.xsd.zillowtypes;
